version: '3.8'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile-whisper
    ports:
      - "8100:8100"
    volumes:
      - ./data:/app/data  # 挂载数据目录以持久化任务状态
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped  # 失败自动重启，除非手动停止
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # 启用GPU支持（如果可用）
